/**
 * Social carousel target.
 *
 * Carousels are fixed-pixel canvases, not fluid layouts. This emits a JSON spec
 * of the common canvas sizes with safe areas, plus a ready-to-render HTML slide
 * template wired to the design tokens. Sizes follow current platform guidance.
 */

import type { DesignTokens } from "../tokens";
import type { OutputFile } from "./index";

interface Canvas {
	name: string;
	width: number;
	height: number;
	/** Inset (px) to keep key content clear of platform UI / cropping. */
	safeArea: number;
}

const CANVASES: Canvas[] = [
	{ name: "instagram-portrait", width: 1080, height: 1350, safeArea: 96 },
	{ name: "instagram-square", width: 1080, height: 1080, safeArea: 96 },
	{ name: "story-9x16", width: 1080, height: 1920, safeArea: 128 },
	{ name: "linkedin-square", width: 1200, height: 1200, safeArea: 100 },
];

function carouselSpec(tokens: DesignTokens): string {
	const spec = {
		name: tokens.name,
		generatedBy: "pi-designer",
		canvases: CANVASES,
		palette: tokens.colors,
		typography: tokens.typography,
		spacing: tokens.spacing,
		guidance: {
			maxHeadingWords: 8,
			body: "Keep one idea per slide. Anchor text inside the safe area.",
			contrast: "Use brand-700+ text on neutral-50, or neutral-50 text on brand-600+.",
		},
	};
	return `${JSON.stringify(spec, null, 2)}\n`;
}

/** A single 1080x1350 slide template driven by inline CSS variables. */
function slideTemplate(tokens: DesignTokens): string {
	return `<!-- ${tokens.name} — carousel slide template (1080x1350). Generated by pi-designer. -->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<style>
  .slide {
    --bg: ${tokens.colors.brand[600]};
    --fg: ${tokens.colors.neutral[50]};
    --accent: ${(tokens.colors.accent ?? tokens.colors.brand)[300]};
    box-sizing: border-box;
    width: 1080px;
    height: 1350px;
    padding: 96px;
    display: flex;
    flex-direction: column;
    justify-content: flex-end;
    background: var(--bg);
    color: var(--fg);
    font-family: ${tokens.typography.fontFamilies.body};
  }
  .slide .eyebrow {
    font-family: ${tokens.typography.fontFamilies.heading};
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: var(--accent);
    font-size: 28px;
    margin: 0 0 24px;
  }
  .slide h1 {
    font-family: ${tokens.typography.fontFamilies.heading};
    font-size: 96px;
    line-height: 1.05;
    margin: 0;
  }
  .slide p { font-size: 40px; line-height: 1.4; margin: 32px 0 0; max-width: 80%; }
</style>
</head>
<body>
  <div class="slide">
    <p class="eyebrow">Eyebrow / series</p>
    <h1>Slide headline goes here</h1>
    <p>Supporting sentence. One idea per slide.</p>
  </div>
</body>
</html>
`;
}

export function carouselTarget(tokens: DesignTokens): OutputFile[] {
	return [
		{ path: "carousel.json", content: carouselSpec(tokens) },
		{ path: "slide-template.html", content: slideTemplate(tokens) },
	];
}
