/**
 * Email newsletter target.
 *
 * Email clients (Outlook especially) have no support for CSS custom properties,
 * rem units, or external stylesheets. Tokens must be emitted as resolved,
 * inline-ready values in px/hex with web-safe font fallbacks, and layout must be
 * table-based. This target produces a flat token JSON plus a skeleton template.
 */

import type { DesignTokens } from "../tokens";
import type { OutputFile } from "./index";

/** rem (16px base) -> integer px, for clients that ignore rem. */
function remToPx(rem: string): number {
	return Math.round(Number.parseFloat(rem) * 16);
}

/** Append web-safe fallbacks so the stack degrades in Outlook/older clients. */
function emailFontStack(stack: string): string {
	const websafe = "Arial, Helvetica, sans-serif";
	return stack.includes("sans-serif") ? stack : `${stack}, ${websafe}`;
}

function emailTokens(tokens: DesignTokens): string {
	const flat = {
		name: tokens.name,
		generatedBy: "pi-designer",
		note: "Inline these values directly on elements. Email clients do not support CSS variables or rem.",
		colors: tokens.colors,
		fonts: {
			heading: emailFontStack(tokens.typography.fontFamilies.heading),
			body: emailFontStack(tokens.typography.fontFamilies.body),
		},
		fontSizesPx: Object.fromEntries(
			Object.entries(tokens.typography.scale).map(([name, step]) => [name, remToPx(step.size)]),
		),
		spacingPx: Object.fromEntries(
			Object.entries(tokens.spacing).map(([key, value]) => [key, remToPx(value)]),
		),
	};
	return `${JSON.stringify(flat, null, 2)}\n`;
}

/** A table-based, inline-styled newsletter skeleton. */
function emailTemplate(tokens: DesignTokens): string {
	const brand = tokens.colors.brand;
	const neutral = tokens.colors.neutral;
	const bodyFont = emailFontStack(tokens.typography.fontFamilies.body);
	const headingFont = emailFontStack(tokens.typography.fontFamilies.heading);
	const bodyPx = remToPx(tokens.typography.scale.base.size);
	const h1Px = remToPx(tokens.typography.scale["2xl"].size);

	return `<!-- ${tokens.name} — newsletter template. Generated by pi-designer. Inline styles only. -->
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /></head>
<body style="margin:0; padding:0; background:${neutral[100]};">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${neutral[100]};">
    <tr>
      <td align="center" style="padding:24px;">
        <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:600px; max-width:600px; background:${neutral[50]}; border-radius:8px;">
          <tr>
            <td style="background:${brand[600]}; padding:32px; border-radius:8px 8px 0 0;">
              <h1 style="margin:0; font-family:${headingFont}; font-size:${h1Px}px; line-height:1.2; color:${neutral[50]};">${tokens.name}</h1>
            </td>
          </tr>
          <tr>
            <td style="padding:32px; font-family:${bodyFont}; font-size:${bodyPx}px; line-height:1.5; color:${neutral[900]};">
              <p style="margin:0 0 16px;">Body copy goes here. Keep paragraphs short.</p>
              <a href="#" style="display:inline-block; background:${brand[600]}; color:${neutral[50]}; text-decoration:none; padding:12px 24px; border-radius:6px; font-family:${headingFont};">Call to action</a>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
`;
}

export function emailTarget(tokens: DesignTokens): OutputFile[] {
	return [
		{ path: "email-tokens.json", content: emailTokens(tokens) },
		{ path: "email-template.html", content: emailTemplate(tokens) },
	];
}
