/** Helpers shared by target exporters. */

import type { DesignTokens } from "../tokens";

/** A `--name: value;` line at a given indent. */
function decl(name: string, value: string, indent = "  "): string {
	return `${indent}${name}: ${value};`;
}

/**
 * Emit CSS custom-property declarations for every token (no selector wrapper).
 * Shared by the website and report targets.
 */
export function cssVariableLines(tokens: DesignTokens, indent = "  "): string[] {
	const lines: string[] = [];

	lines.push(`${indent}/* Colors */`);
	for (const [name, ramp] of Object.entries(tokens.colors)) {
		for (const [stop, hex] of Object.entries(ramp)) {
			lines.push(decl(`--color-${name}-${stop}`, hex, indent));
		}
	}

	lines.push(`${indent}/* Typography */`);
	lines.push(decl("--font-heading", tokens.typography.fontFamilies.heading, indent));
	lines.push(decl("--font-body", tokens.typography.fontFamilies.body, indent));
	lines.push(decl("--font-mono", tokens.typography.fontFamilies.mono, indent));
	for (const [name, step] of Object.entries(tokens.typography.scale)) {
		lines.push(decl(`--text-${name}`, step.size, indent));
		lines.push(decl(`--leading-${name}`, String(step.lineHeight), indent));
	}

	lines.push(`${indent}/* Spacing */`);
	for (const [key, value] of Object.entries(tokens.spacing)) {
		lines.push(decl(`--space-${key.replace(".", "_")}`, value, indent));
	}

	lines.push(`${indent}/* Radii */`);
	for (const [key, value] of Object.entries(tokens.radii)) {
		lines.push(decl(`--radius-${key}`, value, indent));
	}

	lines.push(`${indent}/* Shadows */`);
	for (const [key, value] of Object.entries(tokens.shadows)) {
		lines.push(decl(`--shadow-${key}`, value, indent));
	}

	return lines;
}

/** A short, human-readable header comment for generated files. */
export function fileHeader(tokens: DesignTokens, medium: string): string {
	return `/* ${tokens.name} — ${medium} tokens. Generated by pi-designer. Do not edit by hand. */`;
}
